### ISSUE TITLE
Exercise 1: Multibranch Library

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/mysql_track#4]
https://github.com/segunadeleye/mysql_track/blob/master/Ex1/multibranch_library.sql

Write SQL statements to retrieve the following information:
1. the names of all library books published by Macmillan.
2. branches that hold any books by Ann Brown (using a nested subquery).
3. branches that hold any books by Ann Brown (without using a nested subquery).
4. total number of books held at each branch.

**Comment by Shruti2791** [comment]
Looks fine
Accepting
But try and use inner join in place of natural join as its globally accepted and explicitly show on which columns the join is being applied.
