### ISSUE TITLE
Exercise 3: Article Exercise

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/mysql_track#5]
https://github.com/segunadeleye/mysql_track/blob/master/exercise_3.sql

Design a table structure for following conditions:

A user can write many articles. Each written article will fall under one category. Remember that many articles can be written under same category. The users can be of two types viz. admin or normal. A user can post multiple comments on an article.

Now write queries for: manage categories, articles, comments, and users
- select all articles whose author's name is user3 (Do this exercise using variable also).
- For all the articles being selected above, select all the articles and also the comments associated with those articles in a single query (Do this using subquery also)
- Write a query to select all articles which do not have any comments (Do using subquery also)
- Write a query to select article which has maximum comments
- Write a query to select article which does not have more than one comment by the same user (do this using left join and group by )

**Comment by mkangia** [comment]
Looks Good :+1:
