### ISSUE TITLE
Exercise 1: Sandwich

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/mysql_track#6]
https://github.com/segunadeleye/mysql_track/blob/master/Ex1/sandwich.sql

Write SQL statements to retrieve the following;
1.  places where Jones can eat (using a nested subquery).
2.  places where Jones can eat (without using a nested subquery).
3.  for each location the number of people who can eat there.

**Comment by yuktikhurana** [comment]
Can we add some primary key and foreign key constraints and indexes in all the tables ?

**Comment by segunadeleye** [comment]
Keys added.

**Comment by yuktikhurana** [comment]
Looks good
