### ISSUE TITLE
Exercise 6: Email Campaign Data Exercise

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/mysql_track#7]
https://github.com/segunadeleye/mysql_track/blob/master/exercise_6.sql

We ran a campaign on a website, asking people to submit their email address, their city and phone number.The data was collected in a csv format.­ The file is here... http://dl.dropbox.com/u/628209/exercises/mysql/email_subscribers.txt

First import this csv data into a mysql database. From the database, we need to find the following information by writing a single sql statement for each
- What all cities did people respond from ?
- How many people responded from each city ?
- Which city were the maximum respondents from?
- What all email domains did people respond from ?
- Which is the most popular email domain among the respondents ?

**Comment by Shruti2791** [comment]
1) Inappropriate table name.
2) Why can't we use distinct in query 4 ?
3) Can we have a better method of calculating max ?

**Comment by segunadeleye** [comment]
#### Fixed

I added the new queries just above the old ones for query 3, 4 and 5.

**Comment by Shruti2791** [comment]
This new way is not better than your previous method for calculating max. Lets discuss.

**Comment by Shruti2791** [comment]
looks good
